<?php

namespace Moka\Model;

class CountryModel
{
    static public $countryList=[
        ["name"=> "Afghanistan", "code"=> "AF","id"=>1],
        ["name"=> "Albania", "code"=> "AL","id"=>2],
        ["name"=> "Algeria", "code"=> "DZ","id"=>3],
        ["name"=> "American Samoa", "code"=> "AS","id"=>4],
        ["name"=> "Andorra", "code"=> "AD","id"=>5],
        ["name"=> "Angola", "code"=> "AO","id"=>6],
        ["name"=> "Anguilla", "code"=> "AI","id"=>7],
        ["name"=> "Antarctica", "code"=> "AQ","id"=>8],
        ["name"=> "Antigua and Barbuda", "code"=> "AG","id"=>9],
        ["name"=> "Argentina", "code"=> "AR","id"=>10],
        ["name"=> "Armenia", "code"=> "AM","id"=>11],
        ["name"=> "Aruba", "code"=> "AW","id"=>12],
        ["name"=> "Australia", "code"=> "AU","id"=>13],
        ["name"=> "Austria", "code"=> "AT","id"=>14],
        ["name"=> "Azerbaijan", "code"=> "AZ","id"=>15],
        ["name"=> "Bahamas", "code"=> "BS","id"=>16],
        ["name"=> "Bahrain", "code"=> "BH","id"=>17],
        ["name"=> "Bangladesh", "code"=> "BD","id"=>18],
        ["name"=> "Barbados", "code"=> "BB","id"=>19],
        ["name"=> "Belarus", "code"=> "BY","id"=>20],
        ["name"=> "Belgium", "code"=> "BE","id"=>21],
        ["name"=> "Belize", "code"=> "BZ","id"=>22],
        ["name"=> "Benin", "code"=> "BJ","id"=>23],
        ["name"=> "Bermuda", "code"=> "BM","id"=>24],
        ["name"=> "Bhutan", "code"=> "BT","id"=>25],
        ["name"=> "Bolivia", "code"=> "BO","id"=>26],
        ["name"=> "Bosnia and Herzegovina", "code"=> "BA","id"=>27],
        ["name"=> "Botswana", "code"=> "BW","id"=>28],
        ["name"=> "Brazil", "code"=> "BR","id"=>29],
        ["name"=> "British Virgin Islands", "code"=> "VG","id"=>30],
        ["name"=> "Brunei", "code"=> "BN","id"=>31],
        ["name"=> "Bulgaria", "code"=> "BG","id"=>32],
        ["name"=> "Burkina Faso", "code"=> "BF","id"=>33],
        ["name"=> "Burundi", "code"=> "BI","id"=>34],
        ["name"=> "Cambodia", "code"=> "KH","id"=>35],
        ["name"=> "Cameroon", "code"=> "CM","id"=>36],
        ["name"=> "Canada", "code"=> "CA","id"=>37],
        ["name"=> "Cape Verde", "code"=> "CV","id"=>38],
        ["name"=> "Cayman Islands", "code"=> "KY","id"=>39],
        ["name"=> "Central African Republic", "code"=> "CF","id"=>40],
        ["name"=> "Chad", "code"=> "TD","id"=>41],
        ["name"=> "Chile", "code"=> "CL","id"=>42],
        ["name"=> "China", "code"=> "CN","id"=>43],
        ["name"=> "Christmas Island", "code"=> "CX","id"=>44],
        ["name"=> "Cocos [Keeling] Islands", "code"=> "CC","id"=>45],
        ["name"=> "Colombia", "code"=> "CO","id"=>46],
        ["name"=> "Comoros", "code"=> "KM","id"=>47],
        ["name"=> "Congo [DRC]", "code"=> "CD","id"=>48],
        ["name"=> "Congo [Republic]", "code"=> "CG","id"=>49],
        ["name"=> "Cook Islands", "code"=> "CK","id"=>50],
        ["name"=> "Costa Rica", "code"=> "CR","id"=>51],
        ["name"=> "Croatia", "code"=> "HR","id"=>52],
        ["name"=> "Cuba", "code"=> "CU","id"=>53],
        ["name"=> "Cyprus", "code"=> "CY","id"=>54],
        ["name"=> "Czech Republic", "code"=> "CZ","id"=>55],
        ["name"=> "Denmark", "code"=> "DK","id"=>56],
        ["name"=> "Djibouti", "code"=> "DJ","id"=>57],
        ["name"=> "Dominica", "code"=> "DM","id"=>58],
        ["name"=> "Dominican Republic", "code"=> "DO","id"=>59],
        ["name"=> "East Timor", "code"=> "TL","id"=>60],
        ["name"=> "Ecuador", "code"=> "EC","id"=>61],
        ["name"=> "Egypt", "code"=> "EG","id"=>62],
        ["name"=> "El Salvador", "code"=> "SV","id"=>63],
        ["name"=> "Equatorial Guinea", "code"=> "GQ","id"=>64],
        ["name"=> "Eritrea", "code"=> "ER","id"=>65],
        ["name"=> "Estonia", "code"=> "EE","id"=>66],
        ["name"=> "Ethiopia", "code"=> "ET","id"=>67],
        ["name"=> "Falkland Islands", "code"=> "FK","id"=>68],
        ["name"=> "Faroe Islands", "code"=> "FO","id"=>69],
        ["name"=> "Fiji", "code"=> "FJ","id"=>70],
        ["name"=> "Finland", "code"=> "FI","id"=>71],
        ["name"=> "France", "code"=> "FR","id"=>72],
        ["name"=> "French Guiana", "code"=> "GF","id"=>73],
        ["name"=> "French Polynesia", "code"=> "PF","id"=>74],
        ["name"=> "French Southern Territories", "code"=> "TF","id"=>75],
        ["name"=> "Gabon", "code"=> "GA","id"=>76],
        ["name"=> "Gambia", "code"=> "GM","id"=>77],
        ["name"=> "Georgia", "code"=> "GE","id"=>78],
        ["name"=> "Germany", "code"=> "DE","id"=>79],
        ["name"=> "Ghana", "code"=> "GH","id"=>80],
        ["name"=> "Gibraltar", "code"=> "GI","id"=>81],
        ["name"=> "Greece", "code"=> "GR","id"=>82],
        ["name"=> "Greenland", "code"=> "GL","id"=>83],
        ["name"=> "Grenada", "code"=> "GD","id"=>84],
        ["name"=> "Guadeloupe", "code"=> "GP","id"=>85],
        ["name"=> "Guam", "code"=> "GU","id"=>86],
        ["name"=> "Guatemala", "code"=> "GT","id"=>87],
        ["name"=> "Guinea", "code"=> "GN","id"=>88],
        ["name"=> "Guinea-Bissau", "code"=> "GW","id"=>89],
        ["name"=> "Guyana", "code"=> "GY","id"=>90],
        ["name"=> "Haiti", "code"=> "HT","id"=>91],
        ["name"=> "Honduras", "code"=> "HN","id"=>92],
        ["name"=> "Hong Kong", "code"=> "HK","id"=>93],
        ["name"=> "Hungary", "code"=> "HU","id"=>94],
        ["name"=> "Iceland", "code"=> "IS","id"=>95],
        ["name"=> "India", "code"=> "IN","id"=>96],
        ["name"=> "Indonesia", "code"=> "ID","id"=>97],
        ["name"=> "Iran", "code"=> "IR","id"=>98],
        ["name"=> "Iraq", "code"=> "IQ","id"=>99],
        ["name"=> "Ireland", "code"=> "IE","id"=>100],
        ["name"=> "Isle of Man", "code"=> "IM","id"=>101],
        ["name"=> "Israel", "code"=> "IL","id"=>102],
        ["name"=> "Italy", "code"=> "IT","id"=>103],
        ["name"=> "Ivory Coast", "code"=> "CI","id"=>104],
        ["name"=> "Jamaica", "code"=> "JM","id"=>105],
        ["name"=> "Japan", "code"=> "JP","id"=>106],
        ["name"=> "Jordan", "code"=> "JO","id"=>107],
        ["name"=> "Kazakhstan", "code"=> "KZ","id"=>108],
        ["name"=> "Kenya", "code"=> "KE","id"=>109],
        ["name"=> "Kiribati", "code"=> "KI","id"=>110],
        ["name"=> "Kosovo", "code"=> "XK","id"=>111],
        ["name"=> "Kuwait", "code"=> "KW","id"=>112],
        ["name"=> "Kyrgyzstan", "code"=> "KG","id"=>113],
        ["name"=> "Laos", "code"=> "LA","id"=>114],
        ["name"=> "Latvia", "code"=> "LV","id"=>115],
        ["name"=> "Lebanon", "code"=> "LB","id"=>116],
        ["name"=> "Lesotho", "code"=> "LS","id"=>117],
        ["name"=> "Liberia", "code"=> "LR","id"=>118],
        ["name"=> "Libya", "code"=> "LY","id"=>119],
        ["name"=> "Liechtenstein", "code"=> "LI","id"=>120],
        ["name"=> "Lithuania", "code"=> "LT","id"=>121],
        ["name"=> "Luxembourg", "code"=> "LU","id"=>122],
        ["name"=> "Macau", "code"=> "MO","id"=>123],
        ["name"=> "Macedonia", "code"=> "MK","id"=>124],
        ["name"=> "Madagascar", "code"=> "MG","id"=>125],
        ["name"=> "Malawi", "code"=> "MW","id"=>126],
        ["name"=> "Malaysia", "code"=> "MY","id"=>127],
        ["name"=> "Maldives", "code"=> "MV","id"=>128],
        ["name"=> "Mali", "code"=> "ML","id"=>129],
        ["name"=> "Malta", "code"=> "MT","id"=>130],
        ["name"=> "Marshall Islands", "code"=> "MH","id"=>131],
        ["name"=> "Martinique", "code"=> "MQ","id"=>132],
        ["name"=> "Mauritania", "code"=> "MR","id"=>133],
        ["name"=> "Mauritius", "code"=> "MU","id"=>134],
        ["name"=> "Mayotte", "code"=> "YT","id"=>135],
        ["name"=> "Mexico", "code"=> "MX","id"=>136],
        ["name"=> "Micronesia", "code"=> "FM","id"=>137],
        ["name"=> "Moldova", "code"=> "MD","id"=>138],
        ["name"=> "Monaco", "code"=> "MC","id"=>139],
        ["name"=> "Mongolia", "code"=> "MN","id"=>140],
        ["name"=> "Montserrat", "code"=> "MS","id"=>141],
        ["name"=> "Morocco", "code"=> "MA","id"=>142],
        ["name"=> "Mozambique", "code"=> "MZ","id"=>143],
        ["name"=> "Myanmar [Burma]", "code"=> "MM","id"=>144],
        ["name"=> "Namibia", "code"=> "NA","id"=>145],
        ["name"=> "Nauru", "code"=> "NR","id"=>146],
        ["name"=> "Nepal", "code"=> "NP","id"=>147],
        ["name"=> "Netherlands", "code"=> "NL","id"=>148],
        ["name"=> "Netherlands Antilles", "code"=> "AN","id"=>149],
        ["name"=> "New Caledonia", "code"=> "NC","id"=>150],
        ["name"=> "New Zealand", "code"=> "NZ","id"=>151],
        ["name"=> "Nicaragua", "code"=> "NI","id"=>152],
        ["name"=> "Niger", "code"=> "NE","id"=>153],
        ["name"=> "Nigeria", "code"=> "NG","id"=>154],
        ["name"=> "Niue", "code"=> "NU","id"=>155],
        ["name"=> "Norfolk Island", "code"=> "NF","id"=>156],
        ["name"=> "North Korea", "code"=> "KP","id"=>157],
        ["name"=> "Norway", "code"=> "NO","id"=>158],
        ["name"=> "Oman", "code"=> "OM","id"=>159],
        ["name"=> "Pakistan", "code"=> "PK","id"=>160],
        ["name"=> "Palau", "code"=> "PW","id"=>161],
        ["name"=> "Panama", "code"=> "PA","id"=>162],
        ["name"=> "Papua New Guinea", "code"=> "PG","id"=>163],
        ["name"=> "Paraguay", "code"=> "PY","id"=>164],
        ["name"=> "Peru", "code"=> "PE","id"=>165],
        ["name"=> "Philippines", "code"=> "PH","id"=>166],
        ["name"=> "Pitcairn Islands", "code"=> "PN","id"=>167],
        ["name"=> "Poland", "code"=> "PL","id"=>168],
        ["name"=> "Portugal", "code"=> "PT","id"=>169],
        ["name"=> "Puerto Rico", "code"=> "PR","id"=>170],
        ["name"=> "Qatar", "code"=> "QA","id"=>171],
        ["name"=> "Romania", "code"=> "RO","id"=>173],
        ["name"=> "Russia", "code"=> "RU","id"=>174],
        ["name"=> "Rwanda", "code"=> "RW","id"=>175],
        ["name"=> "Saint Helena", "code"=> "SH","id"=>176],
        ["name"=> "Saint Kitts and Nevis", "code"=> "KN","id"=>177],
        ["name"=> "Saint Lucia", "code"=> "LC","id"=>178],
        ["name"=> "Saint Pierre and Miquelon", "code"=> "PM","id"=>179],
        ["name"=> "Saint Vincent and the Grenadines", "code"=> "VC","id"=>180],
        ["name"=> "San Marino", "code"=> "SM","id"=>181],
        ["name"=> "Sao Tome and Principe", "code"=> "ST","id"=>182],
        ["name"=> "Saudi Arabia", "code"=> "SA","id"=>183],
        ["name"=> "Senegal", "code"=> "SN","id"=>184],
        ["name"=> "Serbia", "code"=> "RS","id"=>185],
        ["name"=> "Seychelles", "code"=> "SC","id"=>186],
        ["name"=> "Sierra Leone", "code"=> "SL","id"=>187],
        ["name"=> "Singapore", "code"=> "SG","id"=>188],
        ["name"=> "Slovakia", "code"=> "SK","id"=>189],
        ["name"=> "Slovenia", "code"=> "SI","id"=>190],
        ["name"=> "Solomon Islands", "code"=> "SB","id"=>191],
        ["name"=> "Somalia", "code"=> "SO","id"=>192],
        ["name"=> "South Africa", "code"=> "ZA","id"=>193],
        ["name"=> "South Korea", "code"=> "KR","id"=>194],
        ["name"=> "Spain", "code"=> "ES","id"=>195],
        ["name"=> "Sri Lanka", "code"=> "LK","id"=>196],
        ["name"=> "Sudan", "code"=> "SD","id"=>197],
        ["name"=> "Suriname", "code"=> "SR","id"=>198],
        ["name"=> "Swaziland", "code"=> "SZ","id"=>199],
        ["name"=> "Sweden", "code"=> "SE","id"=>200],
        ["name"=> "Switzerland", "code"=> "CH","id"=>201],
        ["name"=> "Syria", "code"=> "SY","id"=>202],
        ["name"=> "Taiwan", "code"=> "TW","id"=>203],
        ["name"=> "Tajikistan", "code"=> "TJ","id"=>204],
        ["name"=> "Tanzania", "code"=> "TZ","id"=>205],
        ["name"=> "Thailand", "code"=> "TH","id"=>206],
        ["name"=> "Togo", "code"=> "TG","id"=>207],
        ["name"=> "Tokelau", "code"=> "TK","id"=>208],
        ["name"=> "Tonga", "code"=> "TO","id"=>209],
        ["name"=> "Trinidad and Tobago", "code"=> "TT","id"=>210],
        ["name"=> "Tunisia", "code"=> "TN","id"=>211],
        ["name"=> "TURKIYE", "code"=> "TR","id"=>212],
        ["name"=> "Turkmenistan", "code"=> "TM","id"=>213],
        ["name"=> "Turks and Caicos Islands", "code"=> "TC","id"=>214],
        ["name"=> "Tuvalu", "code"=> "TV","id"=>215],
        ["name"=> "U.S. Virgin Islands", "code"=> "VI","id"=>216],
        ["name"=> "Uganda", "code"=> "UG","id"=>217],
        ["name"=> "Ukraine", "code"=> "UA","id"=>218],
        ["name"=> "United Arab Emirates", "code"=> "AE","id"=>219],
        ["name"=> "United Kingdom", "code"=> "GB","id"=>220],
        ["name"=> "United States", "code"=> "US","id"=>221],
        ["name"=> "Uruguay", "code"=> "UY","id"=>222],
        ["name"=> "Uzbekistan", "code"=> "UZ","id"=>223],
        ["name"=> "Vanuatu", "code"=> "VU","id"=>224],
        ["name"=> "Vatican City", "code"=> "VA","id"=>225],
        ["name"=> "Venezuela", "code"=> "VE","id"=>226],
        ["name"=> "Vietnam", "code"=> "VN","id"=>227],
        ["name"=> "Wallis and Futuna", "code"=> "WF","id"=>228],
        ["name"=> "Yemen", "code"=> "YE","id"=>229],
        ["name"=> "Zambia", "code"=> "ZM","id"=>230],
        ["name"=> "Zimbabwe", "code"=> "ZW","id"=>231],
        ["name"=> "KIBRIS", "code"=> "CY","id"=>232],
    ];

    static public function getCountryIdByCode(string $code){
        $output=null;
        foreach (self::$countryList as $value) {
            if(trim(strtoupper($value['code']))==trim(strtoupper($code))){
                $output=$value['id'];
                break;
            }
        }
        return $output;
    }
    static public function getCountryCodeById($id){
        $output=null;
        foreach (self::$countryList as $value) {
            if(intval($value['id'])==intval($id)){
                $output=$value['code'];
                break;
            }
            
        }
        return $output;
    }
}